FROM golang:1.19.5-alpine3.17 AS builder

WORKDIR /hangulize
COPY . .

RUN apk add --update git
RUN go mod tidy
RUN go build -o /bin/hangulize ./cmd/hangulize

FROM alpine:3.17

# Python과 pip 설치
RUN apk add --update python3 py3-pip

# pycantonese 설치
RUN pip3 install pycantonese

COPY --from=builder /bin/hangulize /bin/hangulize

# CLI 도구를 계속 실행 상태로 유지
CMD ["tail", "-f", "/dev/null"]